---
openvpn_docker_image: "kylemanna/openvpn"
openvpn_data_volume: "ovpn-data"
openvpn_pki_pass: "abcde"
removal_response: "yes"
openvpn_clients:
  - rohit
  - rohit2

openvpn_key_dir: "/home/ec2-user/profiles"