---
- name: Configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install docker
  yum:
    name: docker
    state: latest

- name: service docker
  service:
    name: docker
    state: started
    
- name: install docker SDK
  command: "pip3 install docker"

- name: OpenVPN config
  docker_container:
    name: myownvpn
    image: kylemanna/openvpn
    state: started
    command: "ovpn_genconfig -u udp://{{ public_ip }}:{{ ovpn_port }}"
    recreate: yes
    auto_remove: yes
    volumes:
      - /home/ec2-user/vpn-data:/etc/openvpn

    detach: yes

- name: Initializing PKI
  docker_container:
    name: myownvpn
    image: kylemanna/openvpn
    state: started
    command: "ovpn_initpki"
    interactive: yes
    recreate: yes
    auto_remove: yes
    volumes:
      - /home/ec2-user/vpn-data:/etc/openvpn

    detach: yes

- name: Creating OpenVPN User
  docker_container:
    name: myownvpn
    image: kylemanna/openvpn
    state: started
    command: "easyrsa build-client-full rohit_user nopass"
    recreate: yes
    # auto_remove: yes
    volumes:
      - /home/ec2-user/vpn-data:/etc/openvpn

    detach: yes

# - name: Generating OpenVPN Config file
#   docker_container:
#     name: myownvpn
#     image: kylemanna/openvpn
#     state: started
#     command: "ovpn_getclient rohit_user > rohit_user.ovpn"
#     recreate: yes
#     auto_remove: yes
#     volumes:
#       - /home/ec2-user/vpn-data:/etc/openvpn

#     detach: yes

# - name: Running VPN Server
#   docker_container:
#     name: myownvpn
#     image: kylemanna/openvpn
#     capabilities: NET_ADMIN
#     recreate: yes
#     keep_volumes: yes
#     ports: 
#       - "{{ ovpn_port }}:1194/udp"
#     volumes:
#       - /home/ec2-user/vpn-data:/etc/openvpn

#     detach: yes
