---
- name: Configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install docker
  yum:
    name: docker
    state: latest

- name: service docker
  service:
    name: docker
    state: started
    
- name: install docker SDK
  command: "pip3 install docker"

- name: Print ansible_user
  debug: "msg=Ansible user: '{{ ansible_user }}'" 

- name: Add user to docker group
  command: "sudo usermod -aG docker {{ansible_user}}"