---
- name: Configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install docker
  package:
    name: docker-ce
    state: present

- name: Start docker service
  service:
    name: docker
    state: started

- name: OpenVPN config
  docker_container:
    name: myownvpn
    image: kylemanna/openvpn
    state: started
    recreate: yes
    user: udp://"{{ public_ip }}":"{{ ovpn_port }}"
    auto_remove: true
    ports: 
      - "{{ ovpn_port }}:1194"
    volumes:
      - $PWD/vpn-data:/etc/openvpn